# Generated by Django 5.2.6 on 2025-09-07 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Support",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "settlement",
                    models.CharField(max_length=255, verbose_name="Населённый пункт"),
                ),
                ("branch", models.CharField(max_length=255, verbose_name="Филиал")),
                (
                    "support_number",
                    models.CharField(max_length=50, verbose_name="Номер опоры"),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Название опоры"
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="Адрес")),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=10,
                        max_digits=15,
                        null=True,
                        verbose_name="Долгота",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=10,
                        max_digits=15,
                        null=True,
                        verbose_name="Широта",
                    ),
                ),
                (
                    "commissioning_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата ввода в эксплуатацию"
                    ),
                ),
                (
                    "owner",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Владеющая организация"
                    ),
                ),
                (
                    "material",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Материал несущей конструкции",
                    ),
                ),
            ],
            options={
                "verbose_name": "Опора",
                "verbose_name_plural": "Опоры",
                "ordering": ["settlement", "support_number"],
            },
        ),
    ]
