# Generated by Django 5.2.6 on 2025-09-09 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="support",
            name="comment",
            field=models.TextField(blank=True, verbose_name="Комментарий"),
        ),
        migrations.AddField(
            model_name="support",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="supports/photos/", verbose_name="Фото"
            ),
        ),
        migrations.AddField(
            model_name="support",
            name="status",
            field=models.CharField(
                choices=[
                    ("accepted", "Принят"),
                    ("processing", "В обработке"),
                    ("rejected", "Отклонен"),
                    ("not_started", "Не начат"),
                ],
                default="processing",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
    ]
