# Generated by Django 5.2.6 on 2025-09-13 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_support_comment_support_photo_support_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="support",
            name="status",
            field=models.CharField(
                choices=[
                    ("accepted", "Принят"),
                    ("processing", "В обработке"),
                    ("rejected", "Отклонен"),
                    ("not_started", "Не начат"),
                ],
                default="not_started",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
        migrations.CreateModel(
            name="FieldSupport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="field_supports/photos/%Y/%m/",
                        verbose_name="Фото",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Не начат"),
                            ("processing", "В обработке"),
                            ("accepted", "Принят"),
                            ("rejected", "Отклонен"),
                        ],
                        default="not_started",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="Адрес")),
                (
                    "owner",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Владеющая организация"
                    ),
                ),
                (
                    "material",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Материал несущей конструкции",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Широта",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Долгота",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="field_supports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
            ],
            options={
                "verbose_name": "Полевой объект (опора)",
                "verbose_name_plural": "Полевые объекты (опоры)",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="main_fields_status_7dd1bf_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="main_fields_created_5d5e24_idx"
                    ),
                    models.Index(fields=["owner"], name="main_fields_owner_fef3f4_idx"),
                ],
            },
        ),
    ]
